# Exclude the following from the Jekyll build process.
exclude: ["_assets",
          "CHANGELOG.txt",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "node_modules",
          "package.json", 
          "templates"]
